# Generated by Django 5.0.1 on 2024-02-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_uuid_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
    ]
