# Generated by Django 5.0.1 on 2024-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='example',
            new_name='cart',
        ),
    ]
